# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: hn_api 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "hn_api"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Rahul Hor\u{e9}"]
  s.date = "2014-10-07"
  s.description = "Ruby client for the Hacker News API"
  s.email = "hore.rahul@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/hn/client.rb",
    "lib/hn/configuration.rb",
    "lib/hn/connection.rb",
    "lib/hn/request.rb",
    "lib/hn/version.rb",
    "lib/hn_api.rb",
    "spec/hn_api_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/O-I/hn_api"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.1"
  s.summary = "Ruby wrapper for the Hacker News API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, ["< 0.10", ">= 0.7"])
      s.add_runtime_dependency(%q<faraday_middleware>, ["< 0.10", ">= 0.8"])
      s.add_runtime_dependency(%q<hashie>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<faraday>, ["< 0.10", ">= 0.7"])
      s.add_dependency(%q<faraday_middleware>, ["< 0.10", ">= 0.8"])
      s.add_dependency(%q<hashie>, [">= 0.4.0"])
      s.add_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<faraday>, ["< 0.10", ">= 0.7"])
    s.add_dependency(%q<faraday_middleware>, ["< 0.10", ">= 0.8"])
    s.add_dependency(%q<hashie>, [">= 0.4.0"])
    s.add_dependency(%q<rspec>, ["~> 3.0.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

